# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  id-token: write
  contents: read
  
jobs:
  build:

    runs-on: arc-self-runners

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update && sudo apt install -y maven
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
  kubernetes:
    runs-on: arc-self-runners
#     needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Install AZ CLI'
      run: sudo apt update && sudo apt install -y curl && curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    
    - uses: azure/setup-kubectl@v3
      name: Setup kubectl
        
    - name: 'Az CLI Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        
    - name: 'Populate KUBECONFIG'
      run: mkdir ~/.kube && echo ${{ secrets.KUBECONFIG }} | base64 -d > ~/.kube/config

    - name: 'Run kubectl'
      run: kubectl get pods
